name = "lifeguard-timesheet"
compatibility_date = "2024-11-01"
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "DB"
id = "d687ee5ac1204a52881536957e2222e5"

[vars]
JWT_SECRET = "lifeguard-prod-secret-2026-hk-swimmer"
